version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: LITERALURA_DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ALURA_TEST
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
